Supprime l'affichage de "autre matériel" quand c'est inutile
Robert-2/Robert2 pull request #335
Opened 2022-03-10 10:08 UTC by polosson

2022-03-12 10:40 UTC, Donov4n commented
Le fonctionnement de ce qui est implémenté dans cette PR n'est pas limpide pour moi, notamment la partie Twig, il faudrait qu'on en discute à l'oral parce que j'ai quelques questions.

2022-03-12 10:40 UTC, Donov4n requested changes

2022-03-12 10:40 UTC, Donov4n commented on server/src/App/Lib/Domain/MaterialsData.php
> +            throw new \InvalidArgumentException("Missing categories data.");
Le type d'exception n'est sans doute pas le bon. Plutôt `RuntimeException` ?  

Reste que l'implémentation est un peu ... "spéciale", cette méthode `hasSubcategories` devrait être une méthode de l'entité `Category`.

2022-03-12 10:40 UTC, Donov4n commented on server/src/App/Lib/Domain/MaterialsData.php
> +                    'categoryHasSubcategories' => $this->categoryHasSubcategories($categoryId),
`categoryHasSubcategories ` => `hasSubcategories'`

2022-03-12 10:40 UTC, Donov4n commented on server/src/App/Lib/Domain/MaterialsData.php
> +                    'categoryHasSubcategories' => $this->categoryHasSubcategories($categoryId),
`categoryHasSubcategories`  => `hasSubcategories'`

2022-03-12 10:40 UTC, Donov4n commented on server/src/views/pdf/event-summary-default.twig
> +                        {% endif %}
Dans quel cas une sous-catégorie n'a pas de catégorie ?

2022-03-12 10:40 UTC, Donov4n commented on server/src/views/pdf/event-summary-default.twig
> +                        {% endif %}
Dans quel cas une sous-catégorie n'a pas de catégorie ?

2022-03-12 10:40 UTC, Donov4n commented on server/src/views/pdf/event-summary-default.twig
> +                    {% elseif subCategory['categoryHasSubcategories'] == true %}
```suggestion
                    {% elseif subCategory['hasSubcategories'] %}
```

2022-03-12 10:41 UTC, Donov4n requested changes

2022-03-12 10:41 UTC, Donov4n commented on server/src/views/pdf/event-summary-default.twig
>                      {% endif %}
Je ne pige pas la logique de cette partie, faudrait qu'on en discute.

2022-03-13 17:16 UTC, polosson commented on server/src/views/pdf/event-summary-default.twig
>                      {% endif %}
À refactorer, il faudrait utiliser un bloc différente pour chaque mode de tri, car le mélange des catégories et sous-catégories est incompréhensible.

2022-03-14 18:00 UTC, merged